import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Notification } from "./components/Notification";
import { NotificationPermissionButton } from "./components/Notification";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>{children}</main>
        {/* Add this at the end of your body */}
        <Notification />

        {/* Add this wherever you want the permission button to appear */}
        <div className="fixed bottom-4 right-4">
          <NotificationPermissionButton />
        </div>
      </body>
    </html>
  );
}
